package com.dante.taipeitour.common

const val attractionKey = "attraction"
const val nameKey = "name"
const val zhTw = "zh-tw"
const val zhCn = "zh-cn"
const val en = "en"
const val ja = "ja"
const val ko = "ko"
const val es = "es"
const val id = "id"
const val th = "th"
const val vi = "vi"
const val systemChinesePrefix = "zh"
const val systemEnglishPrefix = "en"
const val systemIndonesianTag = "id-ID"
